### ISSUE TITLE
Research and document git

### ISSUE THREAD

**Issue by emrecalik** [emrecalik/swe573-wikimed-server#1]

**Comment by CihangirOzmus** [comment]
Document links about git-repository management alternatives such as GitHub, Gitlab and Bitbucket  and git gui tools such as SourceTree, GitHub Desktop etc... 

Dont forget to mention about github actions and gitlab ci/cd pipelines. These are the main functionalities which makes huge difference between them.

**Comment by emrecalik** [comment]
Reopened to add suggestions in Cihangir's comment.

**Comment by emrecalik** [comment]
- Links for git repository services and git GUI tools are added.

- GitHub Actions and Gitlab CI&CD features are explained.
